import Foundation
import AppKit

enum CaptureSuite {
    static func pasteboard() -> NSPasteboard {
        let pb = NSPasteboard(name: NSPasteboard.Name("com.keithadler.clipmac.test.\(UUID().uuidString)"))
        pb.clearContents()
        return pb
    }

    static let suite = TestSuite(name: "Capture", cases: [
        TestCase(name: "refusal rules") { t in
            let excluded = ["com.1password.1password"]
            t.equal(Monitor.refusal(types: ["public.utf8-plain-text"], frontBundleID: "com.apple.Safari", secureInput: false, paused: false, excluded: excluded), nil, "ordinary copy allowed")
            t.equal(Monitor.refusal(types: ["public.utf8-plain-text"], frontBundleID: nil, secureInput: false, paused: true, excluded: excluded), .paused, "paused")
            t.equal(Monitor.refusal(types: ["public.utf8-plain-text"], frontBundleID: nil, secureInput: true, paused: false, excluded: excluded), .secureInput, "secure input")
            for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.typeit4me.clipping"] {
                t.equal(Monitor.refusal(types: ["public.utf8-plain-text", type], frontBundleID: nil, secureInput: false, paused: false, excluded: excluded), .concealed, "concealed: \(type)")
            }
            t.equal(Monitor.refusal(types: ["public.utf8-plain-text"], frontBundleID: "com.1password.1password", secureInput: false, paused: false, excluded: excluded), .excludedApp("com.1password.1password"), "excluded app")
            t.equal(Monitor.refusal(types: [], frontBundleID: "com.1password.1password", secureInput: true, paused: true, excluded: excluded), .paused, "paused wins ordering")
            t.equal(Monitor.refusal(size: 10, cap: 100), nil, "under cap")
            t.equal(Monitor.refusal(size: 101, cap: 100), .tooLarge, "over cap")
        },
        TestCase(name: "default exclusion list covers password managers") { t in
            for id in ["com.1password.1password", "com.apple.keychainaccess", "com.bitwarden.desktop", "org.keepassxc.keepassxc", "com.apple.Passwords"] {
                t.check(Prefs.excludedBundleIDs.contains(id), "default excludes \(id)")
            }
            Prefs.excludedBundleIDs = ["com.example.one"]
            t.equal(Prefs.excludedBundleIDs, ["com.example.one"], "user list replaces the default")
        },
        TestCase(name: "read: plain text and links") { t in
            let pb = pasteboard()
            pb.setString("hello there", forType: .string)
            let c = Monitor.read(pb, sourceBundleID: nil, sourceName: nil)
            t.equal(c?.kind, .text, "text kind")
            t.equal(c?.plain, "hello there", "plain")
            t.equal(c?.size, 11, "size is utf8 bytes")
            pb.clearContents(); pb.setString("  https://example.com/a?b=1 \n", forType: .string)
            t.equal(Monitor.read(pb, sourceBundleID: nil, sourceName: nil)?.kind, .url, "bare https link is a url")
            pb.clearContents(); pb.setString("see https://example.com for details", forType: .string)
            t.equal(Monitor.read(pb, sourceBundleID: nil, sourceName: nil)?.kind, .text, "link inside prose is text")
            pb.clearContents(); pb.setString("", forType: .string)
            t.check(Monitor.read(pb, sourceBundleID: nil, sourceName: nil) == nil, "empty string is nothing")
            pb.clearContents()
            t.check(Monitor.read(pb, sourceBundleID: nil, sourceName: nil) == nil, "empty pasteboard is nothing")
        },
        TestCase(name: "read: richest type wins, plain text kept for search") { t in
            let pb = pasteboard()
            let attr = NSAttributedString(string: "Bold heading", attributes: [.font: NSFont.boldSystemFont(ofSize: 18)])
            let rtf = attr.rtf(from: NSRange(location: 0, length: attr.length), documentAttributes: [:])!
            let item = NSPasteboardItem()
            item.setData(rtf, forType: .rtf)
            item.setString("Bold heading", forType: .string)
            item.setData(Data("<b>Bold heading</b>".utf8), forType: .html)
            pb.writeObjects([item])
            let c = Monitor.read(pb, sourceBundleID: nil, sourceName: nil)
            t.equal(c?.kind, .rtf, "rtf beats html and string")
            t.equal(c?.plain, "Bold heading", "plain fallback")
            t.equal(c?.blobType, NSPasteboard.PasteboardType.rtf.rawValue, "blob type recorded")
            t.equal(c?.blobData, rtf, "raw rtf stored")

            pb.clearContents()
            let html = NSPasteboardItem()
            html.setData(Data("<i>x</i>".utf8), forType: .html)
            pb.writeObjects([html])
            let h = Monitor.read(pb, sourceBundleID: nil, sourceName: nil)
            t.equal(h?.kind, .html, "html without string")
            t.equal(h?.plain, "<i>x</i>", "html source is the plain fallback")

            pb.clearContents()
            let rtfOnly = NSPasteboardItem()
            rtfOnly.setData(rtf, forType: .rtf)
            pb.writeObjects([rtfOnly])
            t.equal(Monitor.read(pb, sourceBundleID: nil, sourceName: nil)?.plain, "Bold heading", "plain derived from rtf when no string")
        },
        TestCase(name: "read: images, tiff converted to png") { t in
            let pb = pasteboard()
            let img = NSImage(size: NSSize(width: 8, height: 8))
            img.lockFocus(); NSColor.red.setFill(); NSRect(x: 0, y: 0, width: 8, height: 8).fill(); img.unlockFocus()
            let tiff = img.tiffRepresentation!
            let png = NSBitmapImageRep(data: tiff)!.representation(using: .png, properties: [:])!
            let item = NSPasteboardItem()
            item.setData(png, forType: .png)
            item.setString("alt text", forType: .string)
            pb.writeObjects([item])
            let c = Monitor.read(pb, sourceBundleID: nil, sourceName: nil)
            t.equal(c?.kind, .image, "png kind")
            t.equal(c?.blobData, png, "png bytes kept")
            t.equal(c?.plain, "alt text", "string kept for search")

            pb.clearContents()
            let tiffItem = NSPasteboardItem()
            tiffItem.setData(tiff, forType: .tiff)
            pb.writeObjects([tiffItem])
            let d = Monitor.read(pb, sourceBundleID: nil, sourceName: nil)
            t.equal(d?.kind, .image, "tiff kind")
            t.equal(d?.blobType, NSPasteboard.PasteboardType.png.rawValue, "tiff stored as png")
            t.check((d?.blobData?.count ?? 0) > 0 && d!.blobData!.starts(with: [0x89, 0x50, 0x4E, 0x47]), "png magic bytes")
        },
        TestCase(name: "read: file urls beat everything") { t in
            let pb = pasteboard()
            pb.writeObjects([URL(fileURLWithPath: "/Applications") as NSURL, URL(fileURLWithPath: "/tmp") as NSURL])
            pb.setString("ignored", forType: .string)
            let c = Monitor.read(pb, sourceBundleID: nil, sourceName: nil)
            t.equal(c?.kind, .file, "file kind")
            t.equal(c?.plain, "/Applications\n/tmp", "one path per line")
            let item = Item(id: 1, kind: .file, preview: "", plain: c!.plain, blobHash: nil, blobType: nil, sourceBundleID: nil, sourceName: nil,
                            createdAt: Date(), lastUsedAt: Date(), useCount: 0, pinned: false, keyword: nil, redactionFlags: 0, size: 0, contentHash: "")
            t.equal(item.filePaths, ["/Applications", "/tmp"], "filePaths splits")
        },
        TestCase(name: "preview collapses and truncates") { t in
            t.equal(Item.makePreview("  a  \n\n  b  \n"), "a ⏎ b", "lines joined, blanks dropped")
            let long = Item.makePreview(String(repeating: "x", count: 200), limit: 20)
            t.equal(long.count, 21, "limit plus ellipsis")
            t.check(long.hasSuffix("…"), "ellipsis")
        },
    ])
}
