//  Clip for Mac — clipboard history that refuses to capture secrets.
//  MIT licensed. See LICENSE.
//
//  Pasteboard polling and the capture rules. macOS has no change notification for the pasteboard,
//  so every clipboard manager polls changeCount. 300 ms while someone is at the keyboard, 1 s when
//  locked, on a coalescing DispatchSourceTimer.
//
//  The "never capture" rules below are the product's identity, not options.

import Foundation
import AppKit

@MainActor
final class Monitor: ObservableObject {
    static let shared = Monitor()

    @Published private(set) var paused = false
    @Published private(set) var pausedUntil: Date?
    @Published private(set) var lastSkip: String?          // why the most recent change wasn't kept
    @Published private(set) var lastCaptured: Item?
    @Published private(set) var secureInput = false

    let pasteboard: NSPasteboard
    /// Test hook: replaces the real secure-input check.
    var secureInputProbe: () -> Bool = { Capabilities.secureInputActive }
    /// Test hook: replaces the frontmost-app lookup.
    var frontmostProbe: () -> (bundleID: String?, name: String?) = {
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.bundleIdentifier, app?.localizedName)
    }

    private var timer: DispatchSourceTimer?
    private var lastChangeCount: Int
    private var locked = false
    private var fastInterval = true
    /// changeCounts the app itself produced (paste, restore). Never captured.
    private var ownChangeCounts = Set<Int>()

    nonisolated static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping",
    ]

    private convenience init() { self.init(pasteboard: .general) }

    init(pasteboard: NSPasteboard) {
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
        let dnc = DistributedNotificationCenter.default()
        dnc.addObserver(forName: Notification.Name("com.apple.screenIsLocked"), object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor in self?.locked = true; self?.reschedule() }
        }
        dnc.addObserver(forName: Notification.Name("com.apple.screenIsUnlocked"), object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor in self?.locked = false; self?.reschedule() }
        }
        refreshPauseState()
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        reschedule()
    }

    func stop() { timer?.cancel(); timer = nil }

    private func reschedule() {
        timer?.cancel()
        let t = DispatchSource.makeTimerSource(queue: .main)
        let fast = !locked && fastInterval
        t.schedule(deadline: .now(), repeating: fast ? .milliseconds(300) : .seconds(1), leeway: .milliseconds(fast ? 100 : 400))
        t.setEventHandler { [weak self] in self?.poll() }
        t.resume()
        timer = t
    }

    /// Called by Paster before it writes, so the resulting change isn't captured as a new item.
    func expectOwnChange() { ownChangeCounts.insert(pasteboard.changeCount + 1) }

    // MARK: - Pause

    func pause(for interval: TimeInterval) {
        Prefs.pausedUntil = Date().addingTimeInterval(interval)
        refreshPauseState()
    }

    func resume() { Prefs.pausedUntil = nil; refreshPauseState() }

    private func refreshPauseState() {
        let until = Prefs.pausedUntil
        pausedUntil = until
        paused = until.map { $0 > Date() } ?? false
    }

    // MARK: - Poll

    private var idleTicks = 0

    /// Seconds since the user last touched the keyboard or mouse. A copy needs a keystroke or a click,
    /// so slow polling is only safe while the person is away, never merely because the clipboard is quiet.
    private static var userIdleSeconds: Double {
        min(CGEventSource.secondsSinceLastEventType(.combinedSessionState, eventType: .keyDown),
            CGEventSource.secondsSinceLastEventType(.combinedSessionState, eventType: .leftMouseDown),
            CGEventSource.secondsSinceLastEventType(.combinedSessionState, eventType: .mouseMoved))
    }

    func poll() {
        let pb = pasteboard
        let cc = pb.changeCount
        if cc == lastChangeCount {
            idleTicks += 1
            if idleTicks % 4 == 0 {
                refreshPauseState(); secureInput = secureInputProbe()
                let away = Monitor.userIdleSeconds > 120
                if fastInterval == away { fastInterval = !away; reschedule() }
            }
            return
        }
        idleTicks = 0
        lastChangeCount = cc
        if !fastInterval { fastInterval = true; reschedule() }
        refreshPauseState()
        secureInput = secureInputProbe()

        if ownChangeCounts.remove(cc) != nil { return }
        let front = frontmostProbe()
        let types = Set((pb.types ?? []).map(\.rawValue))
        if let why = Monitor.refusal(types: types, frontBundleID: front.bundleID, secureInput: secureInput, paused: paused) {
            lastSkip = why.description; return
        }
        guard let capture = Monitor.read(pb, sourceBundleID: front.bundleID, sourceName: front.name) else { lastSkip = Refusal.unreadable.description; return }
        if let why = Monitor.refusal(size: capture.size) { lastSkip = why.description; return }

        lastSkip = nil
        let item = Store.shared.insert(capture)
        lastCaptured = item
        Assist.shared.indexSoon()
        NotificationCenter.default.post(name: .clipHistoryChanged, object: nil)
    }

    /// Why a pasteboard change is not kept. Every rule lives here so it can be tested without a pasteboard.
    enum Refusal: Equatable, CustomStringConvertible {
        case paused, secureInput, concealed, excludedApp(String), tooLarge, unreadable

        var description: String {
            switch self {
            case .paused: return String(localized: "paused")
            case .secureInput: return String(localized: "a password field has focus")
            case .concealed: return String(localized: "marked concealed by the source app")
            case .excludedApp: return String(localized: "copied from an excluded app")
            case .tooLarge: return String(localized: "larger than the size cap")
            case .unreadable: return String(localized: "nothing readable on the pasteboard")
            }
        }
    }

    nonisolated static func refusal(types: Set<String>, frontBundleID: String?, secureInput: Bool, paused: Bool,
                                    excluded: [String] = Prefs.excludedBundleIDs) -> Refusal? {
        if paused { return .paused }
        if secureInput { return .secureInput }
        if !types.isDisjoint(with: concealedTypes) { return .concealed }
        if let bid = frontBundleID, excluded.contains(bid) { return .excludedApp(bid) }
        return nil
    }

    nonisolated static func refusal(size: Int, cap: Int = Prefs.sizeCapBytes) -> Refusal? {
        size > cap ? .tooLarge : nil
    }

    /// Reads the richest representation plus a plain-text fallback for search.
    nonisolated static func read(_ pb: NSPasteboard, sourceBundleID bid: String?, sourceName name: String?) -> Capture? {
        let string = pb.string(forType: .string)

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return Capture(kind: .file, plain: paths.joined(separator: "\n"), blobData: nil, blobType: nil,
                           sourceBundleID: bid, sourceName: name, size: paths.joined().utf8.count)
        }
        if let rtf = pb.data(forType: .rtf) {
            let plain = string ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string ?? ""
            return Capture(kind: .rtf, plain: plain, blobData: rtf, blobType: NSPasteboard.PasteboardType.rtf.rawValue,
                           sourceBundleID: bid, sourceName: name, size: rtf.count + plain.utf8.count)
        }
        if let html = pb.data(forType: .html) {
            let plain = string ?? String(data: html, encoding: .utf8) ?? ""
            return Capture(kind: .html, plain: plain, blobData: html, blobType: NSPasteboard.PasteboardType.html.rawValue,
                           sourceBundleID: bid, sourceName: name, size: html.count + plain.utf8.count)
        }
        if let png = pb.data(forType: .png) {
            return Capture(kind: .image, plain: string ?? "", blobData: png, blobType: NSPasteboard.PasteboardType.png.rawValue,
                           sourceBundleID: bid, sourceName: name, size: png.count)
        }
        if let tiff = pb.data(forType: .tiff) {
            // Store PNG when the conversion is cheap; TIFF as a last resort.
            if let rep = NSBitmapImageRep(data: tiff), let png = rep.representation(using: .png, properties: [:]) {
                return Capture(kind: .image, plain: string ?? "", blobData: png, blobType: NSPasteboard.PasteboardType.png.rawValue,
                               sourceBundleID: bid, sourceName: name, size: png.count)
            }
            return Capture(kind: .image, plain: string ?? "", blobData: tiff, blobType: NSPasteboard.PasteboardType.tiff.rawValue,
                           sourceBundleID: bid, sourceName: name, size: tiff.count)
        }
        if let s = string, !s.isEmpty {
            let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
            let isURL = !trimmed.contains(where: \.isWhitespace) && (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://"))
            return Capture(kind: isURL ? .url : .text, plain: s, blobData: nil, blobType: nil,
                           sourceBundleID: bid, sourceName: name, size: s.utf8.count)
        }
        return nil
    }
}

extension Notification.Name {
    static let clipHistoryChanged = Notification.Name("com.keithadler.clipmac.historyChanged")
}
