//  Pasteboard polling and the capture rules. macOS has no change notification for the pasteboard,
//  so every clipboard manager polls changeCount. 300 ms while the Mac is in use, 1 s when idle or
//  locked, on a coalescing DispatchSourceTimer.
//
//  The "never capture" rules below are the product's identity, not options.

import Foundation
import AppKit

@MainActor
final class Monitor: ObservableObject {
    static let shared = Monitor()

    @Published private(set) var paused = false
    @Published private(set) var pausedUntil: Date?
    @Published private(set) var lastSkip: String?          // why the most recent change wasn't kept
    @Published private(set) var lastCaptured: Item?
    @Published private(set) var secureInput = false

    private var timer: DispatchSourceTimer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var locked = false
    private var fastInterval = true
    /// changeCounts the app itself produced (paste, restore). Never captured.
    private var ownChangeCounts = Set<Int>()

    nonisolated static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping",
    ]

    private init() {
        let dnc = DistributedNotificationCenter.default()
        dnc.addObserver(forName: Notification.Name("com.apple.screenIsLocked"), object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor in self?.locked = true; self?.reschedule() }
        }
        dnc.addObserver(forName: Notification.Name("com.apple.screenIsUnlocked"), object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor in self?.locked = false; self?.reschedule() }
        }
        refreshPauseState()
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        reschedule()
    }

    func stop() { timer?.cancel(); timer = nil }

    private func reschedule() {
        timer?.cancel()
        let t = DispatchSource.makeTimerSource(queue: .main)
        let fast = !locked && fastInterval
        t.schedule(deadline: .now(), repeating: fast ? .milliseconds(300) : .seconds(1), leeway: .milliseconds(fast ? 100 : 400))
        t.setEventHandler { [weak self] in self?.poll() }
        t.resume()
        timer = t
    }

    /// Called by Paster before it writes, so the resulting change isn't captured as a new item.
    func expectOwnChange() { ownChangeCounts.insert(NSPasteboard.general.changeCount + 1) }

    // MARK: - Pause

    func pause(for interval: TimeInterval) {
        Prefs.pausedUntil = Date().addingTimeInterval(interval)
        refreshPauseState()
    }

    func resume() { Prefs.pausedUntil = nil; refreshPauseState() }

    private func refreshPauseState() {
        let until = Prefs.pausedUntil
        pausedUntil = until
        paused = until.map { $0 > Date() } ?? false
    }

    // MARK: - Poll

    private var idleTicks = 0

    private func poll() {
        // Idle backoff: nothing has changed for two minutes → 1 s polling until the next change.
        let pb = NSPasteboard.general
        let cc = pb.changeCount
        if cc == lastChangeCount {
            idleTicks += 1
            if fastInterval && idleTicks > 400 { fastInterval = false; reschedule() }
            if idleTicks % 4 == 0 { refreshPauseState(); secureInput = Capabilities.secureInputActive }
            return
        }
        idleTicks = 0
        lastChangeCount = cc
        if !fastInterval { fastInterval = true; reschedule() }
        refreshPauseState()
        secureInput = Capabilities.secureInputActive

        if ownChangeCounts.remove(cc) != nil { return }
        if paused { lastSkip = String(localized: "paused"); return }
        if secureInput { lastSkip = String(localized: "a password field has focus"); return }

        let types = Set((pb.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Monitor.concealedTypes) { lastSkip = String(localized: "marked concealed by the source app"); return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier, Prefs.excludedBundleIDs.contains(bid) {
            lastSkip = String(localized: "copied from an excluded app"); return
        }

        guard let capture = Monitor.read(pb, source: front) else { lastSkip = String(localized: "nothing readable on the pasteboard"); return }
        if capture.size > Prefs.sizeCapBytes { lastSkip = String(localized: "larger than the size cap"); return }

        lastSkip = nil
        let item = Store.shared.insert(capture)
        lastCaptured = item
        Assist.shared.indexSoon()
        NotificationCenter.default.post(name: .clipHistoryChanged, object: nil)
    }

    /// Reads the richest representation plus a plain-text fallback for search.
    static func read(_ pb: NSPasteboard, source: NSRunningApplication?) -> Capture? {
        let bid = source?.bundleIdentifier
        let name = source?.localizedName
        let string = pb.string(forType: .string)

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return Capture(kind: .file, plain: paths.joined(separator: "\n"), blobData: nil, blobType: nil,
                           sourceBundleID: bid, sourceName: name, size: paths.joined().utf8.count)
        }
        if let rtf = pb.data(forType: .rtf) {
            let plain = string ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string ?? ""
            return Capture(kind: .rtf, plain: plain, blobData: rtf, blobType: NSPasteboard.PasteboardType.rtf.rawValue,
                           sourceBundleID: bid, sourceName: name, size: rtf.count + plain.utf8.count)
        }
        if let html = pb.data(forType: .html) {
            let plain = string ?? String(data: html, encoding: .utf8) ?? ""
            return Capture(kind: .html, plain: plain, blobData: html, blobType: NSPasteboard.PasteboardType.html.rawValue,
                           sourceBundleID: bid, sourceName: name, size: html.count + plain.utf8.count)
        }
        if let png = pb.data(forType: .png) {
            return Capture(kind: .image, plain: string ?? "", blobData: png, blobType: NSPasteboard.PasteboardType.png.rawValue,
                           sourceBundleID: bid, sourceName: name, size: png.count)
        }
        if let tiff = pb.data(forType: .tiff) {
            // Store PNG when the conversion is cheap; TIFF as a last resort.
            if let rep = NSBitmapImageRep(data: tiff), let png = rep.representation(using: .png, properties: [:]) {
                return Capture(kind: .image, plain: string ?? "", blobData: png, blobType: NSPasteboard.PasteboardType.png.rawValue,
                               sourceBundleID: bid, sourceName: name, size: png.count)
            }
            return Capture(kind: .image, plain: string ?? "", blobData: tiff, blobType: NSPasteboard.PasteboardType.tiff.rawValue,
                           sourceBundleID: bid, sourceName: name, size: tiff.count)
        }
        if let s = string, !s.isEmpty {
            let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
            let isURL = !trimmed.contains(where: \.isWhitespace) && (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://"))
            return Capture(kind: isURL ? .url : .text, plain: s, blobData: nil, blobType: nil,
                           sourceBundleID: bid, sourceName: name, size: s.utf8.count)
        }
        return nil
    }
}

extension Notification.Name {
    static let clipHistoryChanged = Notification.Name("com.keithadler.clipmac.historyChanged")
}
